language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

before_install:
  - gem install bundler

cache: bundler
sudo: false

services:
  - mysql

addons:
  postgresql: 9.6
  mysql: 5.7

install:
  - createdb test_mini_sql
  - mysql -e 'CREATE DATABASE test_mini_sql;'
  - bundle install

matrix:
  allow_failures:
    - rvm: ruby-head
